# Generated by Django 3.1.7 on 2021-10-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_persononlinedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persononlinedata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='api.person'),
        ),
    ]
