# Generated by Django 3.1.7 on 2021-10-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211007_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persononlinedata',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='api.person'),
        ),
    ]
